version: "3.8"
services:
  # ====================================================================================================================
  # APP
  # ====================================================================================================================
  # docker run -itd --name="app" -v $PWD:/app -w "/app" -p "8080:8080" ????/????-openjdk:17 ./mvnw spring-boot:run
  web:
    image: bellsoft/liberica-runtime-container:jdk-17-slim-musl
    container_name: app
    working_dir: /app
    volumes:
      - $PWD:/app
    ports:
      - 5005:5005
      - ${PORT}:${PORT}
    environment:
      - JAVA_OPTS="-XX:+UseContainerSupport,-Xmx300m,-Xss512k,-XX:CICompilerCount=2,-Dfile.encoding=UTF-8"
    command: [
      /bin/sh, -c, "./mvnw
      spring-boot:run
      -Dspring-boot.run.jvmArguments=$JAVA_OPTS
      -Dspring-boot.run.arguments='--server.port='${PORT}"
    ]
    networks:
      - net

# ======================================================================================================================
# NET
# ======================================================================================================================
networks:
  net:
    driver: bridge