version: "3.8"
services:
  # ====================================================================================================================
  # APP
  # ====================================================================================================================
  # docker run -itd --name="app" -v $PWD:/app -w "/app" -p "8080:8080" ????/????-openjdk:17 ./mvnw spring-boot:run
  web:
    image: ghcr.io/graalvm/graalvm-ce:ol9-java17
    container_name: app
    working_dir: /app
    volumes:
      - $PWD:/app
      - ${HOME}/.m2/repository:/root/.m2/repository
    ports:
      - 5005:5005
      - $PORT:$PORT
    environment:
      PORT: ${PORT}
    command: [
      /bin/sh, -c, "./mvnw spring-boot:run
      -Dspring-boot.run.arguments='--server.port='$PORT"
    ]
    depends_on:
      - sql
    networks:
      - network

  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  sql:
    image: postgres:14-alpine
    container_name: postegres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - network

# ====================================================================================================================
# PGADMIN
# ====================================================================================================================
  sql-cli:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: me@pexample.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - 80:80
    volumes:
      - ./.data/pgadmin:/var/lib/pgdamin
    depends_on:
      - sql
    networks:
      - network

# ======================================================================================================================
# NET
# ======================================================================================================================
networks:
  network:
    driver: bridge