version: "3.8"
services:
  # ====================================================================================================================
  # JDK - RUN APP
  # ====================================================================================================================
  # docker run -itd --name="app" -v $PWD:/app -w "/app" -p "8080:8080" azul/zulu-openjdk:17 ./mvnw spring-boot:run
  web:
    image: azul/zulu-openjdk:17
    container_name: app
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - $PWD:/app
    environment:
      # "-Dserver.port=$PORT", "-Dspring.profiles.active=test"
      - JAVA_OPTS="-XX:+UseContainerSupport, -Xmx300m, -Xss512k, -XX:CICompilerCount=2, -Dfile.encoding=UTF-8"
    working_dir: /app
    command: ["./mvnw", "spring-boot:run"]
    networks:
      - net

# ======================================================================================================================
# NET
# ======================================================================================================================
networks:
  net:
    driver: bridge