version: "3.8"
services:
  # ====================================================================================================================
  # APP
  # ====================================================================================================================
  # docker run -itd --name="app" -v $PWD:/app -w "/app" -p "8080:8080" ????/????-openjdk:17 ./mvnw spring-boot:run
  web:
    image: ghcr.io/graalvm/graalvm-ce:ol9-java17
    container_name: app
    working_dir: /app
    volumes:
      - $PWD:/app
      - ${HOME}/.m2/repository:/root/.m2/repository
    ports:
      - 5005:5005
      - $PORT:$PORT
    environment:
      PORT: ${PORT}
    command: [
      /bin/sh, -c, "./mvnw spring-boot:run
      -Dspring-boot.run.arguments='--server.port='$PORT"
    ]
    networks:
      - net

# ======================================================================================================================
# NET
# ======================================================================================================================
networks:
  net:
    driver: bridge